/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;
import roles.*;
/**
 *
 * @author nacho
 */
public class MenuPrincipal extends javax.swing.JPanel {
Usuario agente;
Ventana ventana;
    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal(Usuario rol, Ventana padre) {
        initComponents();
        this.agente=rol;
        ventana=padre;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MP_Boton_MasterearPartida = new javax.swing.JButton();
        MP_Boton_JuegaPartida = new javax.swing.JButton();
        MP_Boton_ConfiguracionGeneral = new javax.swing.JButton();

        MP_Boton_MasterearPartida.setText("Masterear Partida");
        MP_Boton_MasterearPartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MP_Boton_MasterearPartidaActionPerformed(evt);
            }
        });

        MP_Boton_JuegaPartida.setText("Jugar Partida");
        MP_Boton_JuegaPartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MP_Boton_JuegaPartidaActionPerformed(evt);
            }
        });

        MP_Boton_ConfiguracionGeneral.setText("Configuracion General");
        MP_Boton_ConfiguracionGeneral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MP_Boton_ConfiguracionGeneralActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MP_Boton_MasterearPartida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(MP_Boton_JuegaPartida, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                    .addComponent(MP_Boton_ConfiguracionGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MP_Boton_MasterearPartida)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(MP_Boton_JuegaPartida)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(MP_Boton_ConfiguracionGeneral)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void MP_Boton_MasterearPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MP_Boton_MasterearPartidaActionPerformed
        agente.MP_MasterearPartida(ventana);
    }//GEN-LAST:event_MP_Boton_MasterearPartidaActionPerformed

    private void MP_Boton_JuegaPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MP_Boton_JuegaPartidaActionPerformed
        agente.MP_JugarPartida(ventana);
    }//GEN-LAST:event_MP_Boton_JuegaPartidaActionPerformed

    private void MP_Boton_ConfiguracionGeneralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MP_Boton_ConfiguracionGeneralActionPerformed
        agente.MP_Configuracion(ventana);
    }//GEN-LAST:event_MP_Boton_ConfiguracionGeneralActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton MP_Boton_ConfiguracionGeneral;
    private javax.swing.JButton MP_Boton_JuegaPartida;
    private javax.swing.JButton MP_Boton_MasterearPartida;
    // End of variables declaration//GEN-END:variables
}
