/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import roles.*;

/**
 *
 * @author nacho
 */
public class PantallaJugador extends javax.swing.JPanel {
    
Jugador agente;
    
    /**
     * Creates new form PantallaJugador
     */
    public PantallaJugador(Jugador rol) {
        this.agente = rol;
        PantallaMensajes pm=new PantallaMensajes(rol);
        PantallaSusurros ps=new PantallaSusurros(rol);
        PantallaPrivada pp=new PantallaPrivada(rol);
        DiarioPersonal dp=new DiarioPersonal(rol);
        DiarioGrupal dg=new DiarioGrupal(rol);
        initComponents();
        
        jTabbedPane1.addTab("Mensajes", pm);
        jTabbedPane1.addTab("Susurros", ps);
        jTabbedPane1.addTab("Privados", pp);
        jTabbedPane1.addTab("Diario Personal", dp);
        jTabbedPane1.addTab("Diario Grupal", dg);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("TabPanel");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
